### ISSUE TITLE
pip install error `Unable to find 'libwebp/1.0.3@bincrafters/stable' in remotes`

### ISSUE THREAD

**Issue by AdrianTeng** [anibali/pywebp#28]
When I was running `pip install webp` on my machine (I've tried Mac OSX locally running python 3.9, and Ubuntu 20.04 on Goolge Cloud running python 3.7), the following error occurs.

It seems the fault lies in conan's central repositry having problem?

```
  Using cached webp-0.1.0.tar.gz (10 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-kde4udh1/webp_e50a0efe43e94741af23b6ff41438837/setup.py'"'"'; __file__='"'"'/tmp/pip-install-kde4udh1/webp_e50a0efe43e94741af23b6ff41438837/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-vgixepwg
         cwd: /tmp/pip-install-kde4udh1/webp_e50a0efe43e94741af23b6ff41438837/
    Complete output (71 lines):
    Configuration:
    [settings]
    arch=x86_64
    arch_build=x86_64
    build_type=Release
    compiler=gcc
    compiler.libcxx=libstdc++
    compiler.version=7
    os=Linux
    os_build=Linux
    [options]
    [build_requires]
    [env]

    libwebp/1.0.3@bincrafters/stable: Not found in local cache, looking in remotes...
    libwebp/1.0.3@bincrafters/stable: Trying with 'conancenter'...
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-kde4udh1/webp_e50a0efe43e94741af23b6ff41438837/setup.py", line 24, in <module>
        'License :: OSI Approved :: MIT License',
      File "/usr/local/lib/python3.7/dist-packages/setuptools/__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.7/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/local/lib/python3.7/dist-packages/setuptools/dist.py", line 456, in __init__
        k: v for k, v in attrs.items()
      File "/usr/lib/python3.7/distutils/dist.py", line 292, in __init__
        self.finalize_options()
      File "/usr/local/lib/python3.7/dist-packages/setuptools/dist.py", line 807, in finalize_options
        ep(self)
      File "/usr/local/lib/python3.7/dist-packages/setuptools/dist.py", line 814, in _finalize_setup_keywords
        ep.load()(self, ep.name, value)
      File "/usr/local/lib/python3.7/dist-packages/cffi/setuptools_ext.py", line 219, in cffi_modules
        add_cffi_module(dist, cffi_module)
      File "/usr/local/lib/python3.7/dist-packages/cffi/setuptools_ext.py", line 49, in add_cffi_module
        execfile(build_file_name, mod_vars)
      File "/usr/local/lib/python3.7/dist-packages/cffi/setuptools_ext.py", line 25, in execfile
        exec(code, glob, glob)
      File "webp_build/builder.py", line 14, in <module>
        conan.install(path=getcwd(), cwd=tmp_dir)
      File "/tmp/pip-install-kde4udh1/webp_e50a0efe43e94741af23b6ff41438837/.eggs/conan-1.40.0-py3.7.egg/conans/client/conan_api.py", line 93, in wrapper
        return f(api, *args, **kwargs)
      File "/tmp/pip-install-kde4udh1/webp_e50a0efe43e94741af23b6ff41438837/.eggs/conan-1.40.0-py3.7.egg/conans/client/conan_api.py", line 620, in install
        require_overrides=require_overrides)
      File "/tmp/pip-install-kde4udh1/webp_e50a0efe43e94741af23b6ff41438837/.eggs/conan-1.40.0-py3.7.egg/conans/client/manager.py", line 61, in deps_install
        require_overrides=require_overrides)
      File "/tmp/pip-install-kde4udh1/webp_e50a0efe43e94741af23b6ff41438837/.eggs/conan-1.40.0-py3.7.egg/conans/client/graph/graph_manager.py", line 122, in load_graph
        apply_build_requires=apply_build_requires)
      File "/tmp/pip-install-kde4udh1/webp_e50a0efe43e94741af23b6ff41438837/.eggs/conan-1.40.0-py3.7.egg/conans/client/graph/graph_manager.py", line 282, in _resolve_graph
        graph_lock=graph_lock)
      File "/tmp/pip-install-kde4udh1/webp_e50a0efe43e94741af23b6ff41438837/.eggs/conan-1.40.0-py3.7.egg/conans/client/graph/graph_manager.py", line 385, in _load_graph
        profile_build, graph_lock)
      File "/tmp/pip-install-kde4udh1/webp_e50a0efe43e94741af23b6ff41438837/.eggs/conan-1.40.0-py3.7.egg/conans/client/graph/graph_builder.py", line 67, in load_graph
        update, remotes, profile_host, profile_build, graph_lock)
      File "/tmp/pip-install-kde4udh1/webp_e50a0efe43e94741af23b6ff41438837/.eggs/conan-1.40.0-py3.7.egg/conans/client/graph/graph_builder.py", line 133, in _expand_node
        context_switch=False)
      File "/tmp/pip-install-kde4udh1/webp_e50a0efe43e94741af23b6ff41438837/.eggs/conan-1.40.0-py3.7.egg/conans/client/graph/graph_builder.py", line 249, in _expand_require
        populate_settings_target=populate_settings_target)
      File "/tmp/pip-install-kde4udh1/webp_e50a0efe43e94741af23b6ff41438837/.eggs/conan-1.40.0-py3.7.egg/conans/client/graph/graph_builder.py", line 442, in _create_new_node
        remotes, profile, graph_lock)
      File "/tmp/pip-install-kde4udh1/webp_e50a0efe43e94741af23b6ff41438837/.eggs/conan-1.40.0-py3.7.egg/conans/client/graph/graph_builder.py", line 407, in _resolve_recipe
        raise e
      File "/tmp/pip-install-kde4udh1/webp_e50a0efe43e94741af23b6ff41438837/.eggs/conan-1.40.0-py3.7.egg/conans/client/graph/graph_builder.py", line 402, in _resolve_recipe
        remotes, self._recorder)
      File "/tmp/pip-install-kde4udh1/webp_e50a0efe43e94741af23b6ff41438837/.eggs/conan-1.40.0-py3.7.egg/conans/client/graph/proxy.py", line 37, in get_recipe
        result = self._get_recipe(layout, ref, check_updates, update, remotes, recorder)
      File "/tmp/pip-install-kde4udh1/webp_e50a0efe43e94741af23b6ff41438837/.eggs/conan-1.40.0-py3.7.egg/conans/client/graph/proxy.py", line 54, in _get_recipe
        recorder)
      File "/tmp/pip-install-kde4udh1/webp_e50a0efe43e94741af23b6ff41438837/.eggs/conan-1.40.0-py3.7.egg/conans/client/graph/proxy.py", line 173, in _download_recipe
        raise NotFoundException(msg)
    conans.errors.NotFoundException: Unable to find 'libwebp/1.0.3@bincrafters/stable' in remotes
```

**Comment by anibali** [comment]
Thanks for the report, I was able to reproduce the error. I believe that this may be a result of JFrog ending Bintray (https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/). In any case, the remote which previously provided the libwebp binary no longer works.

I have changed the remote for the libwebp binary in https://github.com/anibali/pywebp/commit/9ab568a841902e9322f38643cf7c2c57281d9a30 which fixed the issue. Expect a new release of webp on PyPI soon.

**Comment by anibali** [comment]
I have released v0.1.2 which should fix this issue.

**Comment by AdrianTeng** [comment]
Can confirm `webp==0.1.2` solves this problem. Thanks!

**Comment by FeraruSilviuMarian** [comment]
strange how that fixed it for you, me I'm still getting an error 

`        raise ConanException("%s: %s" % (ref or "Conanfile", str(e)))
    conans.errors.ConanException: libwebp/1.0.3: 'settings.compiler' value not defined
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/16/60/be7e03cd6423308a5e7bbeace6e7eb612172534734043d8ffbae77862df3/webp-0.1.2.tar.gz#sha256=3d71b890ffdf39dcda02086f28fe66727f06b3a4854ec8e86d1318628c3ff044 (from https://pypi.org/simple/webp/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement webp==0.1.2 (from versions: 0.1.0a4, 0.1.0a5, 0.1.0a6, 0.1.0a7, 0.1.0a9, 0.1.0a10, 0.1.0a11, 0.1.0a12, 0.1.0a13, 0.1.0a14, 0.1.0a15, 0.1.0a16, 0.1.0, 0.1.1, 0.1.2)
ERROR: No matching distribution found for webp==0.1.2`

**Comment by anibali** [comment]
@FeraruSilviuMarian That's a different error, and I think it's now key to your issue in https://github.com/anibali/pywebp/issues/27. Let's continue the discussion there please.
